routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/','IndexController',[
    'only'=>['index'],
    'names'=>[
        'index'=>'home'
    ]
]);

Route::resource('portfolios','PortfolioController',[
    'parameters' => [
        'portfolios' => 'alias'
    ]
]);
Route::resource('articles','ArticlesController',[
    'parameters' => [
        'articles' => 'alias'
    ]
]);

app/Articles.php
<?php

namespace Corp;

use Illuminate\Database\Eloquent\Model;

class Articles extends Model
{
    //
}

app/Filter.php
<?php

namespace Corp;

use Illuminate\Database\Eloquent\Model;

class Filter extends Model
{
    //
}

app/Menu.php
<?php

namespace Corp;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    //
}

app/Portfolio.php
<?php

namespace Corp;

use Illuminate\Database\Eloquent\Model;

class Portfolio extends Model
{
    //
    public function filter()
    {
        return $this->belongsTo('Corp\Filter','filter_alias','alias');
    }
}

app/Slider.php
<?php

namespace Corp;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    //
}

app/User.php
<?php

namespace Corp;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ArticlesController.php
<?php

namespace Corp\Http\Controllers;

use Illuminate\Http\Request;

class ArticlesController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace Corp\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/IndexController.php
<?php

namespace Corp\Http\Controllers;

use Corp\Repositories\ArticlesRepository;
use Corp\Repositories\PortfoliosRepository;
use Corp\Repositories\SlidersRepository;
use Illuminate\Http\Request;
//use Corp\Http\Request;
use Config;

class IndexController extends SiteController
{
    public function __construct(SlidersRepository $s_rep, PortfoliosRepository $p_rep, ArticlesRepository $a_rep)
    {
        parent::__construct(new \Corp\Repositories\MenusRepository(new \Corp\Menu));

        $this->s_rep = $s_rep;
        $this->p_rep = $p_rep;
        $this->a_rep = $a_rep;

        $this->bar = 'right';
        $this->template = env('THEME') . '.index';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $portfolios = $this->getPortfolio();

        $content = view(env('THEME').'.content')->with('portfolios',$portfolios)->render();
        $this->vars = array_add($this->vars,'content',$content);

        $slidersItems = $this->getSliders();

        $sliders = view(env('THEME').'.slider')->with('sliders',$slidersItems)->render();
        $this->vars = array_add($this->vars,'sliders',$sliders);

        $articles = $this->getArticles();
        $this->contentRightBar =  view(env('THEME').'.indexBar')->with('articles',$articles)->render();

        $this->keywords = 'Home Page';
        $this->meta_desc = 'Home Page';
        $this->title = 'Home Page';

        return $this->renderOutput();
    }

    protected function getArticles()
    {
        $articles = $this->a_rep->get(['title','created_at','img','alias'],Config::get('settings.home_articles_count'));
        return $articles;
    }
    protected function getPortfolio()
    {
        $portfolio = $this->p_rep->get('*',Config::get('settings.home_port_count'));
        return $portfolio;
    }
    public function getSliders()
    {
        $sliders = $this->s_rep->get();

        if($sliders->isEmpty()){
            return FALSE;
        }

        $sliders->transform(function ($item, $key) {
            $item->img = Config::get('settings.slider_path').'/'.$item->img;
            return $item;
        });

//        dd($sliders);
        return $sliders;
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/PortfolioController.php
<?php

namespace Corp\Http\Controllers;

use Illuminate\Http\Request;

class PortfolioController extends Controller
{
    //
}

app/Http/Controllers/SiteController.php
<?php

namespace Corp\Http\Controllers;

//use Corp\Menu;
use Corp\Repositories\MenusRepository;
use Corp\Http\Requestes;
use Illuminate\Http\Request;
use Menu;

class SiteController extends Controller
{
    //
    protected $p_rep;
    protected $s_rep;
    protected $a_rep;
    protected $m_rep;

    protected $keywords;
    protected $meta_desc;
    protected $title;

    protected $template;
    protected $vars = array();

    protected $contentRightBar = FALSE;
    protected $contentLeftBar = FALSE;
    protected $bar = 'no';

    public function __construct(MenusRepository $m_rep)
    {
        $this->m_rep = $m_rep;
    }

    protected function renderOutput()
    {

        $menu = $this->getMenu();
        $navigation = view(env('THEME').'.navigation')->with('menu',$menu)->render();

        $this->vars = array_add($this->vars,'navigation',$navigation);

        if($this->contentRightBar){
            $rightBar =  view(env('THEME').'.rightBar')->with('content_rightBar',$this->contentRightBar)->render();
            $this->vars = array_add($this->vars,'rightBar',$rightBar);
        }

        $this->vars = array_add($this->vars,'bar',$this->bar);

        $this->vars = array_add($this->vars,'keywords',$this->keywords);
        $this->vars = array_add($this->vars,'meta_desc',$this->meta_desc);
        $this->vars = array_add($this->vars,'title',$this->title);

        $footer = view(env('THEME').'.footer')->render();
        $this->vars = array_add($this->vars,'footer',$footer);

        return view($this->template)->with($this->vars);
    }

    protected function getMenu()
    {
        $menu = $this->m_rep->get();

        $mBuilder = Menu::make('MaNav', function ($m) use ($menu){

                foreach ($menu as $item){

                    if($item->parent == 0){
                        $m->add($item->title,$item->path)->id($item->id);
                    }else{
                        if($m->find($item->parent)){
                            $m->find($item->parent)->add($item->title,$item->path)->id($item->id);
                        }
                    }

                }

        });

//        dd($mBuilder);

        return $mBuilder;
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/pink/content.blade.php
@if($portfolios && count($portfolios) > 0)
    <div id="content-home" class="content group">
    <div class="hentry group">
        <div class="section portfolio">

            <h3 class="title">{{ trans('ru.latest_projects') }}</h3>

            @foreach($portfolios as $k=>$item)

                @if($k == 0)
                    <div class="hentry work group portfolio-sticky portfolio-full-description">
                        <div class="work-thumbnail">
                            <a class="thumb"><img src="{{asset(env('THEME'))}}/images/projects/{{ $item->img->path }}" alt="0081" title="0081" /></a>
                            <div class="work-overlay">
                                <h3><a href="{{route('portfolios.show',['alias'=>$item->alias])}}">{{ $item->title }}</a></h3>
                                <p class="work-overlay-categories"><img src="{{asset(env('THEME'))}}/images/categories.png" alt="Categories" /> in: <a href="#">{{ $item->filter->title }}</a></p>
                            </div>
                        </div>
                        <div class="work-description">
                            <h2><a href="{{route('portfolios.show',['alias'=>$item->alias])}}">{{ $item->title }}</a></h2>
                            <p class="work-categories">in: <a href="#">{{ $item->filter->title }}</a></p>
                           <p>{!! str_limit($item->text,200) !!}</p>

                                <a href="{{route('portfolios.show',['alias'=>$item->alias])}}" class="read-more">|| {{ trans('ru.read_more') }}</a>
                        </div>
                    </div>

                    <div class="clear"></div>

                    @continue
                @endif


            @if($k == 1)
            <div class="portfolio-projects">
            @endif
                <div class="related_project {{ ($k == 4) ? ' related_project_last' : '' }}">
                    <div class="overlay_a related_img">
                        <div class="overlay_wrapper">
                            <img src="{{asset(env('THEME'))}}/images/projects/{{ $item->img->mini }}" alt="0061" title="0061" />
                            <div class="overlay">
                                <a class="overlay_img" href="{{asset(env('THEME'))}}/images/projects/{{ $item->img->path }}" rel="lightbox" title=""></a>
                                <a class="overlay_project" href="{{route('portfolios.show',['alias'=>$item->alias])}}"></a>
                                <span class="overlay_title">{{ $item->title }}</span>
                            </div>
                        </div>
                    </div>
                    <h4><a href="{{route('portfolios.show',['alias'=>$item->alias])}}">{{ $item->title }}</a></h4>
                    <p>{!! str_limit($item->text,200) !!}</p>
                </div>
                @endforeach

            </div>

        </div>
        <div class="clear"></div>
    </div>
    <!-- START COMMENTS -->
    <div id="comments">
    </div>
    <!-- END COMMENTS -->
</div>
@else
<p>empty</p>
@endif

resources/views/pink/customMenuItems.blade.php
@foreach($items as $item)
    <li {{ (URL::current() == $item->url()) ? "class=active" : '' }}>
        <a href="{{ $item->url() }}">{{ $item->title }}</a>
        @if($item->hasChildren())
            <ul class="sub-menu">
                @include(env('THEME').'.customMenuItems',['items'=>$item->children()])
            </ul>
        @endif
    </li>
@endforeach

resources/views/pink/footer.blade.php
<div id="copyright">
    <div class="inner group">
        <div class="left">
            <a href="http://yithemes.com/?ddownload=2046&ap_id=pinkrio-html"><strong>Download the free version for Wordpress</strong></a>
        </div>
        <div class="right">
            <a href="#" class="socials-small facebook-small" title="Facebook">facebook</a>
            <a href="#" class="socials-small rss-small" title="Rss">rss</a>
            <a href="#" class="socials-small twitter-small" title="Twitter">twitter</a>
            <a href="#" class="socials-small flickr-small" title="Flickr">flickr</a>
            <a href="#" class="socials-small skype-small" title="Skype">skype</a>
            <a href="#" class="socials-small google-small" title="Google">google</a>
            <a href="#" class="socials-small pinterest-small" title="Pinterest">pinterest</a>
        </div>
    </div>
</div>

resources/views/pink/index.blade.php
@extends(env('THEME').'.layouts.site')

@section('navigation')
    {!! $navigation !!}
@endsection

@section('slider')
    {!! $sliders !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

@section('bar')
    {!! $rightBar !!}
@endsection
@section('footer')
    {!! $footer !!}
@endsection

resources/views/pink/indexBar.blade.php
    <div class="widget-first widget recent-posts">
        @if($articles)
            <h3>{{trans('ru.form_blog')}}</h3>
            <div class="recent-post group">

                @foreach($articles as $article)
                    <div class="hentry-post group">
                        <div class="thumb-img"><img src="{{asset(env('THEME'))}}/images/articles/{{ $article->img->mini }}" alt="001" title="001" /></div>
                        <div class="text">
                            <a href="{{ route('articles.show',['alias'=>$article->alias]) }}" title="Section shortcodes &amp; sticky posts!" class="title">{{ $article->title }}</a>
                            <p class="post-date">{{ $article->created_at->format('F d, Y') }}</p>
                        </div>
                    </div>
                @endforeach
            </div>
        @endif

    </div>

    <div class="widget-last widget text-image">
        <h3>Customer support</h3>
        <div class="text-image" style="text-align:left"><img src="{{asset(env('THEME'))}}/images/callus.gif" alt="Customer support" /></div>
        <p>Proin porttitor dolor eu nibh lacinia at ultrices lorem venenatis. Sed volutpat scelerisque vulputate. </p>
    </div>

resources/views/pink/layouts/site.blade.php
<!DOCTYPE html>
<!--[if IE 6]>
<html id="ie6" class="ie" dir="ltr" lang="en-US">
<![endif]-->
<!--[if IE 7]>
<html id="ie7" class="ie" dir="ltr" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html id="ie8" class="ie" dir="ltr" lang="en-US">
<![endif]-->
<!--[if IE 9]>
<html id="ie9" class="ie" dir="ltr" lang="en-US">
<![endif]-->
<!--[if gt IE 9]>
<html class="ie" dir="ltr" lang="en-US">
<![endif]-->
<!--[if !IE]>
<html dir="ltr" lang="en-US">
<![endif]-->

<!-- START HEAD -->
<head>

    <meta charset="UTF-8" />
    <!-- this line will appear only if the website is visited with an iPad -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.2, user-scalable=yes" />
    <meta name="description" content="{{ (isset($meta_desc)) ? $meta_desc : '' }}" />
    <meta name="keywords" content="{{ (isset($keywords)) ? $keywords : '' }}" />

    <title>{{ $title or 'Pink' }}</title>

    <!-- [favicon] begin -->
    <link rel="shortcut icon" type="image/x-icon" href="{{asset(env('THEME'))}}/images/favicon.ico" />
    <link rel="icon" type="image/x-icon" href="{{asset(env('THEME'))}}/images/favicon.ico" />
    <!-- Touch icons more info: http://mathiasbynens.be/notes/touch-icons -->
    <!-- For iPad3 with retina display: -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{asset(env('THEME'))}}/apple-touch-icon-144x.png" />
    <!-- For first- and second-generation iPad: -->
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{asset(env('THEME'))}}/apple-touch-icon-114x.png" />
    <!-- For first- and second-generation iPad: -->
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{asset(env('THEME'))}}/apple-touch-icon-72x.png" />
    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <link rel="apple-touch-icon-precomposed" href="{{asset(env('THEME'))}}/apple-touch-icon-57x.png" />
    <!-- [favicon] end -->

    <!-- CSSs -->
    <link rel="stylesheet" type="text/css" media="all" href="{{asset(env('THEME'))}}/css/reset.css" /> <!-- RESET STYLESHEET -->
    <link rel="stylesheet" type="text/css" media="all" href="{{asset(env('THEME'))}}/style.css" /> <!-- MAIN THEME STYLESHEET -->
    <link rel="stylesheet" id="max-width-1024-css" href="{{asset(env('THEME'))}}/css/max-width-1024.css" type="text/css" media="screen and (max-width: 1240px)" />
    <link rel="stylesheet" id="max-width-768-css" href="{{asset(env('THEME'))}}/css/max-width-768.css" type="text/css" media="screen and (max-width: 987px)" />
    <link rel="stylesheet" id="max-width-480-css" href="{{asset(env('THEME'))}}/css/max-width-480.css" type="text/css" media="screen and (max-width: 480px)" />
    <link rel="stylesheet" id="max-width-320-css" href="{{asset(env('THEME'))}}/css/max-width-320.css" type="text/css" media="screen and (max-width: 320px)" />

    <!-- CSSs Plugin -->
    <link rel="stylesheet" id="thickbox-css" href="{{asset(env('THEME'))}}/css/thickbox.css" type="text/css" media="all" />
    <link rel="stylesheet" id="styles-minified-css" href="{{asset(env('THEME'))}}/css/style-minifield.css" type="text/css" media="all" />
    <link rel="stylesheet" id="buttons" href="{{asset(env('THEME'))}}/css/buttons.css" type="text/css" media="all" />
    <link rel="stylesheet" id="cache-custom-css" href="{{asset(env('THEME'))}}/css/cache-custom.css" type="text/css" media="all" />
    <link rel="stylesheet" id="custom-css" href="{{asset(env('THEME'))}}/css/custom.css" type="text/css" media="all" />

    <!-- FONTs -->
    <link rel="stylesheet" id="google-fonts-css" href="http://fonts.googleapis.com/css?family=Oswald%7CDroid+Sans%7CPlayfair+Display%7COpen+Sans+Condensed%3A300%7CRokkitt%7CShadows+Into+Light%7CAbel%7CDamion%7CMontez&amp;ver=3.4.2" type="text/css" media="all" />
    <link rel='stylesheet' href='{{asset(env('THEME'))}}/css/font-awesome.css' type='text/css' media='all' />

    <!-- JAVASCRIPTs -->
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/comment-reply.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.quicksand.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.tipsy.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.cycle.min.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.anythingslider.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.eislideshow.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.easing.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.flexslider-min.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.aw-showcase.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/layerslider.kreaturamedia.jquery-min.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/shortcodes.js"></script>
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.colorbox-min.js"></script> <!-- nav -->
    <script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.tweetable.js"></script>

</head>
<!-- END HEAD -->

<!-- START BODY -->
<body class="no_js responsive page-template-home-php stretched">

<!-- START BG SHADOW -->
<div class="bg-shadow">

    <!-- START WRAPPER -->
    <div id="wrapper" class="group">

        <!-- START HEADER -->
        <div id="header" class="group">

            <div class="group inner">

                <!-- START LOGO -->
                <div id="logo" class="group">
                    <a href="index.html" title="Pink Rio"><img src="{{asset(env('THEME'))}}/images/logo.png" title="Pink Rio" alt="Pink Rio" /></a>
                </div>
                <!-- END LOGO -->

                <div id="sidebar-header" class="group">
                    <div class="widget-first widget yit_text_quote">
                        <blockquote class="text-quote-quote">&#8220;The caterpillar does all the work but the butterfly gets all the publicity.&#8221;</blockquote>
                        <cite class="text-quote-author">George Carlin</cite>
                    </div>
                </div>
                <div class="clearer"></div>

                <hr />

                <!-- START MAIN NAVIGATION -->
                @yield('navigation')
                <!-- END MAIN NAVIGATION -->
                <div id="header-shadow"></div>
                <div id="menu-shadow"></div>
            </div>

        </div>
        <!-- END HEADER -->

        <!-- START SLIDER -->
            @yield('slider')
        <!-- START PRIMARY -->
        <div id="primary" class="sidebar-{{ isset ( $bar ) ? $bar : 'no' }}">
            <div class="inner group">
                <!-- START CONTENT -->
                @yield('content')
                <!-- END CONTENT -->
                <!-- START SIDEBAR -->
                @yield('bar')
                <!-- END SIDEBAR -->
                <!-- START EXTRA CONTENT -->
                <!-- END EXTRA CONTENT -->
            </div>
        </div>
        <!-- END PRIMARY -->

        <!-- START COPYRIGHT -->
            @yield('footer')
        <!-- END COPYRIGHT -->
    </div>
    <!-- END WRAPPER -->
</div>
<!-- END BG SHADOW -->

<script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.custom.js"></script>
<script type="text/javascript" src="{{asset(env('THEME'))}}/js/contact.js"></script>
<script type="text/javascript" src="{{asset(env('THEME'))}}/js/jquery.mobilemenu.js"></script>

</body>
<!-- END BODY -->
</html>

resources/views/pink/navigation.blade.php
@if($menu)
    <div class="menu classic">
        <ul id="nav" class="menu">
            @include(env('THEME').'.customMenuItems',['items'=>$menu->roots()])
        </ul>
    </div>
@endif

resources/views/pink/rightBar.blade.php
<div class="sidebar group">
    {!! $content_rightBar !!}
</div>